/* Auto-generated by genmsg_cpp for file /home/asd/MyRosPack/amtec/srv/SetPosition.srv */
#ifndef AMTEC_SERVICE_SETPOSITION_H
#define AMTEC_SERVICE_SETPOSITION_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace amtec
{
template <class ContainerAllocator>
struct SetPositionRequest_ : public ros::Message
{
  typedef SetPositionRequest_<ContainerAllocator> Type;

  SetPositionRequest_()
  : position_pan(0.0)
  , position_tilt(0.0)
  {
  }

  SetPositionRequest_(const ContainerAllocator& _alloc)
  : position_pan(0.0)
  , position_tilt(0.0)
  {
  }

  typedef double _position_pan_type;
  double position_pan;

  typedef double _position_tilt_type;
  double position_tilt;


private:
  static const char* __s_getDataType_() { return "amtec/SetPositionRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "cefac8c7f126ab41b3e46de351ef0cea"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "cefac8c7f126ab41b3e46de351ef0cea"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 position_pan\n\
float64 position_tilt\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, position_pan);
    ros::serialization::serialize(stream, position_tilt);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, position_pan);
    ros::serialization::deserialize(stream, position_tilt);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(position_pan);
    size += ros::serialization::serializationLength(position_tilt);
    return size;
  }

  typedef boost::shared_ptr< ::amtec::SetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amtec::SetPositionRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SetPositionRequest
typedef  ::amtec::SetPositionRequest_<std::allocator<void> > SetPositionRequest;

typedef boost::shared_ptr< ::amtec::SetPositionRequest> SetPositionRequestPtr;
typedef boost::shared_ptr< ::amtec::SetPositionRequest const> SetPositionRequestConstPtr;


template <class ContainerAllocator>
struct SetPositionResponse_ : public ros::Message
{
  typedef SetPositionResponse_<ContainerAllocator> Type;

  SetPositionResponse_()
  {
  }

  SetPositionResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "amtec/SetPositionResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "cefac8c7f126ab41b3e46de351ef0cea"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::amtec::SetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amtec::SetPositionResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SetPositionResponse
typedef  ::amtec::SetPositionResponse_<std::allocator<void> > SetPositionResponse;

typedef boost::shared_ptr< ::amtec::SetPositionResponse> SetPositionResponsePtr;
typedef boost::shared_ptr< ::amtec::SetPositionResponse const> SetPositionResponseConstPtr;

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetPosition
} // namespace amtec

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::amtec::SetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cefac8c7f126ab41b3e46de351ef0cea";
  }

  static const char* value(const  ::amtec::SetPositionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcefac8c7f126ab41ULL;
  static const uint64_t static_value2 = 0xb3e46de351ef0ceaULL;
};

template<class ContainerAllocator>
struct DataType< ::amtec::SetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/SetPositionRequest";
  }

  static const char* value(const  ::amtec::SetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::amtec::SetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 position_pan\n\
float64 position_tilt\n\
\n\
";
  }

  static const char* value(const  ::amtec::SetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::amtec::SetPositionRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::amtec::SetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::amtec::SetPositionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::amtec::SetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/SetPositionResponse";
  }

  static const char* value(const  ::amtec::SetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::amtec::SetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::amtec::SetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::amtec::SetPositionResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::amtec::SetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position_pan);
    stream.next(m.position_tilt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetPositionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::amtec::SetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetPositionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<amtec::SetPosition> {
  static const char* value() 
  {
    return "cefac8c7f126ab41b3e46de351ef0cea";
  }

  static const char* value(const amtec::SetPosition&) { return value(); } 
};

template<>
struct DataType<amtec::SetPosition> {
  static const char* value() 
  {
    return "amtec/SetPosition";
  }

  static const char* value(const amtec::SetPosition&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<amtec::SetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cefac8c7f126ab41b3e46de351ef0cea";
  }

  static const char* value(const amtec::SetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<amtec::SetPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/SetPosition";
  }

  static const char* value(const amtec::SetPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<amtec::SetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cefac8c7f126ab41b3e46de351ef0cea";
  }

  static const char* value(const amtec::SetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<amtec::SetPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/SetPosition";
  }

  static const char* value(const amtec::SetPositionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AMTEC_SERVICE_SETPOSITION_H

