/* Auto-generated by genmsg_cpp for file /home/asd/MyRosPack/amtec/srv/TargetAcceleration.srv */
#ifndef AMTEC_SERVICE_TARGETACCELERATION_H
#define AMTEC_SERVICE_TARGETACCELERATION_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace amtec
{
template <class ContainerAllocator>
struct TargetAccelerationRequest_ : public ros::Message
{
  typedef TargetAccelerationRequest_<ContainerAllocator> Type;

  TargetAccelerationRequest_()
  : acceleration_pan(0.0)
  , acceleration_tilt(0.0)
  {
  }

  TargetAccelerationRequest_(const ContainerAllocator& _alloc)
  : acceleration_pan(0.0)
  , acceleration_tilt(0.0)
  {
  }

  typedef double _acceleration_pan_type;
  double acceleration_pan;

  typedef double _acceleration_tilt_type;
  double acceleration_tilt;


private:
  static const char* __s_getDataType_() { return "amtec/TargetAccelerationRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d342e69bfc77177d150eaee5d0f71f06"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d342e69bfc77177d150eaee5d0f71f06"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 acceleration_pan\n\
float64 acceleration_tilt\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, acceleration_pan);
    ros::serialization::serialize(stream, acceleration_tilt);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, acceleration_pan);
    ros::serialization::deserialize(stream, acceleration_tilt);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(acceleration_pan);
    size += ros::serialization::serializationLength(acceleration_tilt);
    return size;
  }

  typedef boost::shared_ptr< ::amtec::TargetAccelerationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amtec::TargetAccelerationRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct TargetAccelerationRequest
typedef  ::amtec::TargetAccelerationRequest_<std::allocator<void> > TargetAccelerationRequest;

typedef boost::shared_ptr< ::amtec::TargetAccelerationRequest> TargetAccelerationRequestPtr;
typedef boost::shared_ptr< ::amtec::TargetAccelerationRequest const> TargetAccelerationRequestConstPtr;


template <class ContainerAllocator>
struct TargetAccelerationResponse_ : public ros::Message
{
  typedef TargetAccelerationResponse_<ContainerAllocator> Type;

  TargetAccelerationResponse_()
  {
  }

  TargetAccelerationResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "amtec/TargetAccelerationResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d342e69bfc77177d150eaee5d0f71f06"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::amtec::TargetAccelerationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amtec::TargetAccelerationResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct TargetAccelerationResponse
typedef  ::amtec::TargetAccelerationResponse_<std::allocator<void> > TargetAccelerationResponse;

typedef boost::shared_ptr< ::amtec::TargetAccelerationResponse> TargetAccelerationResponsePtr;
typedef boost::shared_ptr< ::amtec::TargetAccelerationResponse const> TargetAccelerationResponseConstPtr;

struct TargetAcceleration
{

typedef TargetAccelerationRequest Request;
typedef TargetAccelerationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct TargetAcceleration
} // namespace amtec

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::amtec::TargetAccelerationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d342e69bfc77177d150eaee5d0f71f06";
  }

  static const char* value(const  ::amtec::TargetAccelerationRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd342e69bfc77177dULL;
  static const uint64_t static_value2 = 0x150eaee5d0f71f06ULL;
};

template<class ContainerAllocator>
struct DataType< ::amtec::TargetAccelerationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/TargetAccelerationRequest";
  }

  static const char* value(const  ::amtec::TargetAccelerationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::amtec::TargetAccelerationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 acceleration_pan\n\
float64 acceleration_tilt\n\
\n\
";
  }

  static const char* value(const  ::amtec::TargetAccelerationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::amtec::TargetAccelerationRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::amtec::TargetAccelerationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::amtec::TargetAccelerationResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::amtec::TargetAccelerationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/TargetAccelerationResponse";
  }

  static const char* value(const  ::amtec::TargetAccelerationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::amtec::TargetAccelerationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::amtec::TargetAccelerationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::amtec::TargetAccelerationResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::amtec::TargetAccelerationRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.acceleration_pan);
    stream.next(m.acceleration_tilt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TargetAccelerationRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::amtec::TargetAccelerationResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TargetAccelerationResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<amtec::TargetAcceleration> {
  static const char* value() 
  {
    return "d342e69bfc77177d150eaee5d0f71f06";
  }

  static const char* value(const amtec::TargetAcceleration&) { return value(); } 
};

template<>
struct DataType<amtec::TargetAcceleration> {
  static const char* value() 
  {
    return "amtec/TargetAcceleration";
  }

  static const char* value(const amtec::TargetAcceleration&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<amtec::TargetAccelerationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d342e69bfc77177d150eaee5d0f71f06";
  }

  static const char* value(const amtec::TargetAccelerationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<amtec::TargetAccelerationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/TargetAcceleration";
  }

  static const char* value(const amtec::TargetAccelerationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<amtec::TargetAccelerationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d342e69bfc77177d150eaee5d0f71f06";
  }

  static const char* value(const amtec::TargetAccelerationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<amtec::TargetAccelerationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amtec/TargetAcceleration";
  }

  static const char* value(const amtec::TargetAccelerationResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AMTEC_SERVICE_TARGETACCELERATION_H

